/* 
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.2.4
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using BlueRain.ID4i.Client;
using BlueRain.ID4i.Api;
using BlueRain.ID4i.Model;

namespace BlueRain.ID4i.Test
{
    /// <summary>
    ///  Class for testing BillingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BillingApiTests
    {
        private BillingApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BillingApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillingApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BillingApi
            //Assert.IsInstanceOfType(typeof(BillingApi), instance, "instance is a BillingApi");
        }

        
        /// <summary>
        /// Test GetPositionsForOrganization
        /// </summary>
        [Test]
        public void GetPositionsForOrganizationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? organizationId = null;
            //DateTime? fromDate = null;
            //DateTime? toDate = null;
            //var response = instance.GetPositionsForOrganization(organizationId, fromDate, toDate);
            //Assert.IsInstanceOf<List<BillingPosition>> (response, "response is List<BillingPosition>");
        }
        
        /// <summary>
        /// Test GetSumForOrganization
        /// </summary>
        [Test]
        public void GetSumForOrganizationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? organizationId = null;
            //DateTime? fromDate = null;
            //DateTime? toDate = null;
            //var response = instance.GetSumForOrganization(organizationId, fromDate, toDate);
            //Assert.IsInstanceOf<ServiceCosts> (response, "response is ServiceCosts");
        }
        
    }

}
