/* 
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.2.4
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using BlueRain.ID4i.Client;
using BlueRain.ID4i.Api;
using BlueRain.ID4i.Model;

namespace BlueRain.ID4i.Test
{
    /// <summary>
    ///  Class for testing WhoIsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WhoIsApiTests
    {
        private WhoIsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WhoIsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WhoIsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WhoIsApi
            //Assert.IsInstanceOfType(typeof(WhoIsApi), instance, "instance is a WhoIsApi");
        }

        
        /// <summary>
        /// Test ResolveWhoIsEntry
        /// </summary>
        [Test]
        public void ResolveWhoIsEntryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id4n = null;
            //var response = instance.ResolveWhoIsEntry(id4n);
            //Assert.IsInstanceOf<WhoIsResponse> (response, "response is WhoIsResponse");
        }
        
    }

}
