/* 
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.2.5-SNAPSHOT
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueRain.ID4i.Api;
using BlueRain.ID4i.Model;
using BlueRain.ID4i.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueRain.ID4i.Test
{
    /// <summary>
    ///  Class for testing AccountCredentials
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountCredentialsTests
    {
        // TODO uncomment below to declare an instance variable for AccountCredentials
        //private AccountCredentials instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountCredentials
            //instance = new AccountCredentials();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountCredentials
        /// </summary>
        [Test]
        public void AccountCredentialsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountCredentials
            //Assert.IsInstanceOfType<AccountCredentials> (instance, "variable 'instance' is a AccountCredentials");
        }


        /// <summary>
        /// Test the property 'Login'
        /// </summary>
        [Test]
        public void LoginTest()
        {
            // TODO unit test for the property 'Login'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

    }

}
