/* 
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.2.4
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueRain.ID4i.Api;
using BlueRain.ID4i.Model;
using BlueRain.ID4i.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueRain.ID4i.Test
{
    /// <summary>
    ///  Class for testing ApiKeyPrivilegePaginatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiKeyPrivilegePaginatedResponseTests
    {
        // TODO uncomment below to declare an instance variable for ApiKeyPrivilegePaginatedResponse
        //private ApiKeyPrivilegePaginatedResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiKeyPrivilegePaginatedResponse
            //instance = new ApiKeyPrivilegePaginatedResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiKeyPrivilegePaginatedResponse
        /// </summary>
        [Test]
        public void ApiKeyPrivilegePaginatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiKeyPrivilegePaginatedResponse
            //Assert.IsInstanceOfType<ApiKeyPrivilegePaginatedResponse> (instance, "variable 'instance' is a ApiKeyPrivilegePaginatedResponse");
        }


        /// <summary>
        /// Test the property 'Elements'
        /// </summary>
        [Test]
        public void ElementsTest()
        {
            // TODO unit test for the property 'Elements'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Test]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
