/* 
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.2.5-SNAPSHOT
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueRain.ID4i.Api;
using BlueRain.ID4i.Model;
using BlueRain.ID4i.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueRain.ID4i.Test
{
    /// <summary>
    ///  Class for testing ApiKeyPrivilege
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiKeyPrivilegeTests
    {
        // TODO uncomment below to declare an instance variable for ApiKeyPrivilege
        //private ApiKeyPrivilege instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiKeyPrivilege
            //instance = new ApiKeyPrivilege();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiKeyPrivilege
        /// </summary>
        [Test]
        public void ApiKeyPrivilegeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiKeyPrivilege
            //Assert.IsInstanceOfType<ApiKeyPrivilege> (instance, "variable 'instance' is a ApiKeyPrivilege");
        }


        /// <summary>
        /// Test the property 'Id4nAssociated'
        /// </summary>
        [Test]
        public void Id4nAssociatedTest()
        {
            // TODO unit test for the property 'Id4nAssociated'
        }
        /// <summary>
        /// Test the property 'Privilege'
        /// </summary>
        [Test]
        public void PrivilegeTest()
        {
            // TODO unit test for the property 'Privilege'
        }

    }

}
