/* 
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.2.4-SNAPSHOT
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueRain.ID4i.Api;
using BlueRain.ID4i.Model;
using BlueRain.ID4i.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueRain.ID4i.Test
{
    /// <summary>
    ///  Class for testing AppInfoPresentation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppInfoPresentationTests
    {
        // TODO uncomment below to declare an instance variable for AppInfoPresentation
        //private AppInfoPresentation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppInfoPresentation
            //instance = new AppInfoPresentation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppInfoPresentation
        /// </summary>
        [Test]
        public void AppInfoPresentationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppInfoPresentation
            //Assert.IsInstanceOfType<AppInfoPresentation> (instance, "variable 'instance' is a AppInfoPresentation");
        }


        /// <summary>
        /// Test the property 'Branch'
        /// </summary>
        [Test]
        public void BranchTest()
        {
            // TODO unit test for the property 'Branch'
        }
        /// <summary>
        /// Test the property 'CommitTime'
        /// </summary>
        [Test]
        public void CommitTimeTest()
        {
            // TODO unit test for the property 'CommitTime'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Revision'
        /// </summary>
        [Test]
        public void RevisionTest()
        {
            // TODO unit test for the property 'Revision'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }

    }

}
