/* 
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.2.4-SNAPSHOT
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueRain.ID4i.Api;
using BlueRain.ID4i.Model;
using BlueRain.ID4i.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueRain.ID4i.Test
{
    /// <summary>
    ///  Class for testing InputStreamResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InputStreamResourceTests
    {
        // TODO uncomment below to declare an instance variable for InputStreamResource
        //private InputStreamResource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InputStreamResource
            //instance = new InputStreamResource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InputStreamResource
        /// </summary>
        [Test]
        public void InputStreamResourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InputStreamResource
            //Assert.IsInstanceOfType<InputStreamResource> (instance, "variable 'instance' is a InputStreamResource");
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Test]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Test]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
        /// <summary>
        /// Test the property 'InputStream'
        /// </summary>
        [Test]
        public void InputStreamTest()
        {
            // TODO unit test for the property 'InputStream'
        }
        /// <summary>
        /// Test the property 'Open'
        /// </summary>
        [Test]
        public void OpenTest()
        {
            // TODO unit test for the property 'Open'
        }
        /// <summary>
        /// Test the property 'Readable'
        /// </summary>
        [Test]
        public void ReadableTest()
        {
            // TODO unit test for the property 'Readable'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
