/* 
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.2.5-SNAPSHOT
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueRain.ID4i.Api;
using BlueRain.ID4i.Model;
using BlueRain.ID4i.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueRain.ID4i.Test
{
    /// <summary>
    ///  Class for testing ListOfId4ns
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListOfId4nsTests
    {
        // TODO uncomment below to declare an instance variable for ListOfId4ns
        //private ListOfId4ns instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListOfId4ns
            //instance = new ListOfId4ns();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListOfId4ns
        /// </summary>
        [Test]
        public void ListOfId4nsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListOfId4ns
            //Assert.IsInstanceOfType<ListOfId4ns> (instance, "variable 'instance' is a ListOfId4ns");
        }


        /// <summary>
        /// Test the property 'Id4ns'
        /// </summary>
        [Test]
        public void Id4nsTest()
        {
            // TODO unit test for the property 'Id4ns'
        }

    }

}
