/* 
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.2.5-SNAPSHOT
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueRain.ID4i.Api;
using BlueRain.ID4i.Model;
using BlueRain.ID4i.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueRain.ID4i.Test
{
    /// <summary>
    ///  Class for testing OrganizationUserInvitation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrganizationUserInvitationTests
    {
        // TODO uncomment below to declare an instance variable for OrganizationUserInvitation
        //private OrganizationUserInvitation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrganizationUserInvitation
            //instance = new OrganizationUserInvitation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrganizationUserInvitation
        /// </summary>
        [Test]
        public void OrganizationUserInvitationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrganizationUserInvitation
            //Assert.IsInstanceOfType<OrganizationUserInvitation> (instance, "variable 'instance' is a OrganizationUserInvitation");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Test]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

    }

}
