/* 
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.2.5-SNAPSHOT
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueRain.ID4i.Api;
using BlueRain.ID4i.Model;
using BlueRain.ID4i.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueRain.ID4i.Test
{
    /// <summary>
    ///  Class for testing RoutingFileRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RoutingFileRequestTests
    {
        // TODO uncomment below to declare an instance variable for RoutingFileRequest
        //private RoutingFileRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RoutingFileRequest
            //instance = new RoutingFileRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RoutingFileRequest
        /// </summary>
        [Test]
        public void RoutingFileRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RoutingFileRequest
            //Assert.IsInstanceOfType<RoutingFileRequest> (instance, "variable 'instance' is a RoutingFileRequest");
        }


        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Test]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }
        /// <summary>
        /// Test the property 'Routing'
        /// </summary>
        [Test]
        public void RoutingTest()
        {
            // TODO unit test for the property 'Routing'
        }

    }

}
