/* 
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.2.5-SNAPSHOT
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueRain.ID4i.Api;
using BlueRain.ID4i.Model;
using BlueRain.ID4i.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueRain.ID4i.Test
{
    /// <summary>
    ///  Class for testing Visibility
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VisibilityTests
    {
        // TODO uncomment below to declare an instance variable for Visibility
        //private Visibility instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Visibility
            //instance = new Visibility();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Visibility
        /// </summary>
        [Test]
        public void VisibilityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Visibility
            //Assert.IsInstanceOfType<Visibility> (instance, "variable 'instance' is a Visibility");
        }


        /// <summary>
        /// Test the property '_Public'
        /// </summary>
        [Test]
        public void _PublicTest()
        {
            // TODO unit test for the property '_Public'
        }
        /// <summary>
        /// Test the property 'SharedOrganizationIds'
        /// </summary>
        [Test]
        public void SharedOrganizationIdsTest()
        {
            // TODO unit test for the property 'SharedOrganizationIds'
        }

    }

}
