/* 
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.2.4-SNAPSHOT
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueRain.ID4i.Api;
using BlueRain.ID4i.Model;
using BlueRain.ID4i.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueRain.ID4i.Test
{
    /// <summary>
    ///  Class for testing WhoIsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WhoIsResponseTests
    {
        // TODO uncomment below to declare an instance variable for WhoIsResponse
        //private WhoIsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WhoIsResponse
            //instance = new WhoIsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WhoIsResponse
        /// </summary>
        [Test]
        public void WhoIsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WhoIsResponse
            //Assert.IsInstanceOfType<WhoIsResponse> (instance, "variable 'instance' is a WhoIsResponse");
        }


        /// <summary>
        /// Test the property 'Aliases'
        /// </summary>
        [Test]
        public void AliasesTest()
        {
            // TODO unit test for the property 'Aliases'
        }
        /// <summary>
        /// Test the property 'Organization'
        /// </summary>
        [Test]
        public void OrganizationTest()
        {
            // TODO unit test for the property 'Organization'
        }
        /// <summary>
        /// Test the property 'OrganizationAddress'
        /// </summary>
        [Test]
        public void OrganizationAddressTest()
        {
            // TODO unit test for the property 'OrganizationAddress'
        }

    }

}
