/* 
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.7.1
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
    using RestSharp.Portable;
using BlueRain.ID4i.Client;
using BlueRain.ID4i.Model;
using Guid = BlueRain.ID4i.Model.Guid;

namespace BlueRain.ID4i.Api
{
    /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
    public interface IAliasApi : IApiAccessor
    {
    #region Synchronous Operations
        /// <summary>
            /// Add alias for GUIDs
            /// </summary>
        /// <remarks>
            /// Adds or replaces aliases for single GUIDs (alias type item and mapp) or groups of GUIDs (alias types gtin, ean and article)
            /// </remarks>
        /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id4n">The GUID to operate on</param>
        /// <param name="aliasType">Alias type, see the corresponding API model</param>
        /// <param name="alias">The alias to add or update</param>
        /// <returns></returns>
        void AddGuidAlias (string id4n, string aliasType, GuidAlias alias);

        /// <summary>
            /// Add alias for GUIDs
            /// </summary>
        /// <remarks>
            /// Adds or replaces aliases for single GUIDs (alias type item and mapp) or groups of GUIDs (alias types gtin, ean and article)
            /// </remarks>
        /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id4n">The GUID to operate on</param>
        /// <param name="aliasType">Alias type, see the corresponding API model</param>
        /// <param name="alias">The alias to add or update</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddGuidAliasWithHttpInfo (string id4n, string aliasType, GuidAlias alias);
        /// <summary>
            /// List all supported alias types
            /// </summary>
        /// <remarks>
            /// Retrieve this list to find out all alias types to use with alias search and change operations
            /// </remarks>
        /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;string&gt;</returns>
        List<string> GetGuidAliasTypes ();

        /// <summary>
            /// List all supported alias types
            /// </summary>
        /// <remarks>
            /// Retrieve this list to find out all alias types to use with alias search and change operations
            /// </remarks>
        /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;string&gt;</returns>
        ApiResponse<List<string>> GetGuidAliasTypesWithHttpInfo ();
        /// <summary>
            /// Get all aliases for the given GUID.
            /// </summary>
        /// <remarks>
            /// Looks up the alias for each alias type (group and single GUID) and returns a map of all aliases found.
            /// </remarks>
        /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id4n">The GUID to operate on</param>
        /// <returns>Dictionary&lt;string, string&gt;</returns>
        Dictionary<string, string> GetGuidAliases (string id4n);

        /// <summary>
            /// Get all aliases for the given GUID.
            /// </summary>
        /// <remarks>
            /// Looks up the alias for each alias type (group and single GUID) and returns a map of all aliases found.
            /// </remarks>
        /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id4n">The GUID to operate on</param>
        /// <returns>ApiResponse of Dictionary&lt;string, string&gt;</returns>
        ApiResponse<Dictionary<string, string>> GetGuidAliasesWithHttpInfo (string id4n);
        /// <summary>
            /// Remove aliases from GUIDs
            /// </summary>
        /// <remarks>
            /// Remove the alias of the given type
            /// </remarks>
        /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id4n">The GUID to operate on</param>
        /// <param name="aliasType">Alias type, see the corresponding API model</param>
        /// <returns></returns>
        void RemoveGuidAlias (string id4n, string aliasType);

        /// <summary>
            /// Remove aliases from GUIDs
            /// </summary>
        /// <remarks>
            /// Remove the alias of the given type
            /// </remarks>
        /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id4n">The GUID to operate on</param>
        /// <param name="aliasType">Alias type, see the corresponding API model</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> RemoveGuidAliasWithHttpInfo (string id4n, string aliasType);
        /// <summary>
            /// Search for GUIDs by alias
            /// </summary>
        /// <remarks>
            /// 
            /// </remarks>
        /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alias">The alias to search for</param>
        /// <param name="aliasType">Alias type type to search for</param>
        /// <param name="offset">Start with the n-th element (optional)</param>
        /// <param name="limit">The maximum count of returned elements (optional)</param>
        /// <returns>PaginatedGuidResponse</returns>
        PaginatedGuidResponse SearchByAlias (string alias, string aliasType, int? offset = null, int? limit = null);

        /// <summary>
            /// Search for GUIDs by alias
            /// </summary>
        /// <remarks>
            /// 
            /// </remarks>
        /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alias">The alias to search for</param>
        /// <param name="aliasType">Alias type type to search for</param>
        /// <param name="offset">Start with the n-th element (optional)</param>
        /// <param name="limit">The maximum count of returned elements (optional)</param>
        /// <returns>ApiResponse of PaginatedGuidResponse</returns>
        ApiResponse<PaginatedGuidResponse> SearchByAliasWithHttpInfo (string alias, string aliasType, int? offset = null, int? limit = null);
        #endregion Synchronous Operations
            #region Asynchronous Operations
                /// <summary>
                /// Add alias for GUIDs
                /// </summary>
                /// <remarks>
                /// Adds or replaces aliases for single GUIDs (alias type item and mapp) or groups of GUIDs (alias types gtin, ean and article)
                /// </remarks>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="id4n">The GUID to operate on</param>
            /// <param name="aliasType">Alias type, see the corresponding API model</param>
            /// <param name="alias">The alias to add or update</param>
            /// <returns>Task of void</returns>
            System.Threading.Tasks.Task AddGuidAliasAsync (string id4n, string aliasType, GuidAlias alias);

                /// <summary>
                /// Add alias for GUIDs
                /// </summary>
                /// <remarks>
                /// Adds or replaces aliases for single GUIDs (alias type item and mapp) or groups of GUIDs (alias types gtin, ean and article)
                /// </remarks>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="id4n">The GUID to operate on</param>
            /// <param name="aliasType">Alias type, see the corresponding API model</param>
            /// <param name="alias">The alias to add or update</param>
            /// <returns>Task of ApiResponse</returns>
                System.Threading.Tasks.Task<ApiResponse<Object>> AddGuidAliasAsyncWithHttpInfo (string id4n, string aliasType, GuidAlias alias);
                /// <summary>
                /// List all supported alias types
                /// </summary>
                /// <remarks>
                /// Retrieve this list to find out all alias types to use with alias search and change operations
                /// </remarks>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <returns>Task of List&lt;string&gt;</returns>
            System.Threading.Tasks.Task<List<string>> GetGuidAliasTypesAsync ();

                /// <summary>
                /// List all supported alias types
                /// </summary>
                /// <remarks>
                /// Retrieve this list to find out all alias types to use with alias search and change operations
                /// </remarks>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <returns>Task of ApiResponse (List&lt;string&gt;)</returns>
                System.Threading.Tasks.Task<ApiResponse<List<string>>> GetGuidAliasTypesAsyncWithHttpInfo ();
                /// <summary>
                /// Get all aliases for the given GUID.
                /// </summary>
                /// <remarks>
                /// Looks up the alias for each alias type (group and single GUID) and returns a map of all aliases found.
                /// </remarks>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="id4n">The GUID to operate on</param>
            /// <returns>Task of Dictionary&lt;string, string&gt;</returns>
            System.Threading.Tasks.Task<Dictionary<string, string>> GetGuidAliasesAsync (string id4n);

                /// <summary>
                /// Get all aliases for the given GUID.
                /// </summary>
                /// <remarks>
                /// Looks up the alias for each alias type (group and single GUID) and returns a map of all aliases found.
                /// </remarks>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="id4n">The GUID to operate on</param>
            /// <returns>Task of ApiResponse (Dictionary&lt;string, string&gt;)</returns>
                System.Threading.Tasks.Task<ApiResponse<Dictionary<string, string>>> GetGuidAliasesAsyncWithHttpInfo (string id4n);
                /// <summary>
                /// Remove aliases from GUIDs
                /// </summary>
                /// <remarks>
                /// Remove the alias of the given type
                /// </remarks>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="id4n">The GUID to operate on</param>
            /// <param name="aliasType">Alias type, see the corresponding API model</param>
            /// <returns>Task of void</returns>
            System.Threading.Tasks.Task RemoveGuidAliasAsync (string id4n, string aliasType);

                /// <summary>
                /// Remove aliases from GUIDs
                /// </summary>
                /// <remarks>
                /// Remove the alias of the given type
                /// </remarks>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="id4n">The GUID to operate on</param>
            /// <param name="aliasType">Alias type, see the corresponding API model</param>
            /// <returns>Task of ApiResponse</returns>
                System.Threading.Tasks.Task<ApiResponse<Object>> RemoveGuidAliasAsyncWithHttpInfo (string id4n, string aliasType);
                /// <summary>
                /// Search for GUIDs by alias
                /// </summary>
                /// <remarks>
                /// 
                /// </remarks>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="alias">The alias to search for</param>
            /// <param name="aliasType">Alias type type to search for</param>
            /// <param name="offset">Start with the n-th element (optional)</param>
            /// <param name="limit">The maximum count of returned elements (optional)</param>
            /// <returns>Task of PaginatedGuidResponse</returns>
            System.Threading.Tasks.Task<PaginatedGuidResponse> SearchByAliasAsync (string alias, string aliasType, int? offset = null, int? limit = null);

                /// <summary>
                /// Search for GUIDs by alias
                /// </summary>
                /// <remarks>
                /// 
                /// </remarks>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="alias">The alias to search for</param>
            /// <param name="aliasType">Alias type type to search for</param>
            /// <param name="offset">Start with the n-th element (optional)</param>
            /// <param name="limit">The maximum count of returned elements (optional)</param>
            /// <returns>Task of ApiResponse (PaginatedGuidResponse)</returns>
                System.Threading.Tasks.Task<ApiResponse<PaginatedGuidResponse>> SearchByAliasAsyncWithHttpInfo (string alias, string aliasType, int? offset = null, int? limit = null);
            #endregion Asynchronous Operations
        }

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
    public partial class AliasApi : IAliasApi
        {
        private BlueRain.ID4i.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AliasApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AliasApi(String basePath)
        {
        this.Configuration = new Configuration { BasePath = basePath };

        ExceptionFactory = BlueRain.ID4i.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AliasApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AliasApi(Configuration configuration = null)
        {
        if (configuration == null) // use the default one in Configuration
        this.Configuration = Configuration.Default;
        else
        this.Configuration = configuration;

        ExceptionFactory = BlueRain.ID4i.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
        return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
        // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public BlueRain.ID4i.Client.ExceptionFactory ExceptionFactory
        {
        get
        {
        if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
        {
        throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
        }
        return _exceptionFactory;
        }
        set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
        return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
        this.Configuration.AddDefaultHeader(key, value);
        }

            /// <summary>
            /// Add alias for GUIDs Adds or replaces aliases for single GUIDs (alias type item and mapp) or groups of GUIDs (alias types gtin, ean and article)
            /// </summary>
            /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id4n">The GUID to operate on</param>
        /// <param name="aliasType">Alias type, see the corresponding API model</param>
        /// <param name="alias">The alias to add or update</param>
        /// <returns></returns>
            public void AddGuidAlias (string id4n, string aliasType, GuidAlias alias)
            {
        AddGuidAliasWithHttpInfo(id4n, aliasType, alias);
            }

            /// <summary>
            /// Add alias for GUIDs Adds or replaces aliases for single GUIDs (alias type item and mapp) or groups of GUIDs (alias types gtin, ean and article)
            /// </summary>
            /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id4n">The GUID to operate on</param>
        /// <param name="aliasType">Alias type, see the corresponding API model</param>
        /// <param name="alias">The alias to add or update</param>
        /// <returns>ApiResponse of Object(void)</returns>
            public ApiResponse<Object> AddGuidAliasWithHttpInfo (string id4n, string aliasType, GuidAlias alias)
            {
                    // verify the required parameter 'id4n' is set
                    if (id4n == null)
                    throw new ApiException(400, "Missing required parameter 'id4n' when calling AliasApi->AddGuidAlias");
                    // verify the required parameter 'aliasType' is set
                    if (aliasType == null)
                    throw new ApiException(400, "Missing required parameter 'aliasType' when calling AliasApi->AddGuidAlias");
                    // verify the required parameter 'alias' is set
                    if (alias == null)
                    throw new ApiException(400, "Missing required parameter 'alias' when calling AliasApi->AddGuidAlias");

            var localVarPath = "./api/v1/guids/{id4n}/alias/{aliasType}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/xml", 
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml",
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

                if (id4n != null) localVarPathParams.Add("id4n", Configuration.ApiClient.ParameterToString(id4n)); // path parameter
                if (aliasType != null) localVarPathParams.Add("aliasType", Configuration.ApiClient.ParameterToString(aliasType)); // path parameter
                if (alias != null && alias.GetType() != typeof(byte[]))
                {
                localVarPostBody = Configuration.ApiClient.Serialize(alias); // http body (model) parameter
                }
                else
                {
                localVarPostBody = alias; // byte array
                }

                // authentication (Authorization) required
                        if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
                        {
                        localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
                        }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
            Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
            Exception exception = ExceptionFactory("AddGuidAlias", localVarResponse);
            if (exception != null) throw exception;
            }

                return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                null);
            }

                /// <summary>
                /// Add alias for GUIDs Adds or replaces aliases for single GUIDs (alias type item and mapp) or groups of GUIDs (alias types gtin, ean and article)
                /// </summary>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="id4n">The GUID to operate on</param>
            /// <param name="aliasType">Alias type, see the corresponding API model</param>
            /// <param name="alias">The alias to add or update</param>
            /// <returns>Task of void</returns>
            public async System.Threading.Tasks.Task AddGuidAliasAsync (string id4n, string aliasType, GuidAlias alias)
                {
            await AddGuidAliasAsyncWithHttpInfo(id4n, aliasType, alias);

                }

                /// <summary>
                /// Add alias for GUIDs Adds or replaces aliases for single GUIDs (alias type item and mapp) or groups of GUIDs (alias types gtin, ean and article)
                /// </summary>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="id4n">The GUID to operate on</param>
            /// <param name="aliasType">Alias type, see the corresponding API model</param>
            /// <param name="alias">The alias to add or update</param>
            /// <returns>Task of ApiResponse</returns>
                public async System.Threading.Tasks.Task<ApiResponse<Object>> AddGuidAliasAsyncWithHttpInfo (string id4n, string aliasType, GuidAlias alias)
                {
                        // verify the required parameter 'id4n' is set
                        if (id4n == null)
                        throw new ApiException(400, "Missing required parameter 'id4n' when calling AliasApi->AddGuidAlias");
                        // verify the required parameter 'aliasType' is set
                        if (aliasType == null)
                        throw new ApiException(400, "Missing required parameter 'aliasType' when calling AliasApi->AddGuidAlias");
                        // verify the required parameter 'alias' is set
                        if (alias == null)
                        throw new ApiException(400, "Missing required parameter 'alias' when calling AliasApi->AddGuidAlias");

                var localVarPath = "./api/v1/guids/{id4n}/alias/{aliasType}";
                var localVarPathParams = new Dictionary<String, String>();
                var localVarQueryParams = new List<KeyValuePair<String, String>>();
                var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
                var localVarFormParams = new Dictionary<String, String>();
                var localVarFileParams = new Dictionary<String, FileParameter>();
                Object localVarPostBody = null;

                // to determine the Content-Type header
                String[] localVarHttpContentTypes = new String[] {
                    "application/xml", 
                    "application/json"
                };
                String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

                // to determine the Accept header
                String[] localVarHttpHeaderAccepts = new String[] {
                    "application/xml",
                    "application/json"
                };
                String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
                if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

                    if (id4n != null) localVarPathParams.Add("id4n", Configuration.ApiClient.ParameterToString(id4n)); // path parameter
                    if (aliasType != null) localVarPathParams.Add("aliasType", Configuration.ApiClient.ParameterToString(aliasType)); // path parameter
                    if (alias != null && alias.GetType() != typeof(byte[]))
                    {
                    localVarPostBody = Configuration.ApiClient.Serialize(alias); // http body (model) parameter
                    }
                    else
                    {
                    localVarPostBody = alias; // byte array
                    }

                    // authentication (Authorization) required
                            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
                            {
                            localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
                            }

                // make the HTTP request
                IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

                int localVarStatusCode = (int) localVarResponse.StatusCode;

                if (ExceptionFactory != null)
                {
                Exception exception = ExceptionFactory("AddGuidAlias", localVarResponse);
                if (exception != null) throw exception;
                }

                    return new ApiResponse<Object>(localVarStatusCode,
                    localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                    null);
                }

            /// <summary>
            /// List all supported alias types Retrieve this list to find out all alias types to use with alias search and change operations
            /// </summary>
            /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;string&gt;</returns>
            public List<string> GetGuidAliasTypes ()
            {
        ApiResponse<List<string>> localVarResponse = GetGuidAliasTypesWithHttpInfo();
            return localVarResponse.Data;
            }

            /// <summary>
            /// List all supported alias types Retrieve this list to find out all alias types to use with alias search and change operations
            /// </summary>
            /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;string&gt;</returns>
            public ApiResponse< List<string> > GetGuidAliasTypesWithHttpInfo ()
            {

            var localVarPath = "./api/v1/search/guids/aliases/types";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/xml", 
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml",
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


                // authentication (Authorization) required
                        if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
                        {
                        localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
                        }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
            Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
            Exception exception = ExceptionFactory("GetGuidAliasTypes", localVarResponse);
            if (exception != null) throw exception;
            }

                return new ApiResponse<List<string>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (List<string>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<string>)));
            }

                /// <summary>
                /// List all supported alias types Retrieve this list to find out all alias types to use with alias search and change operations
                /// </summary>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <returns>Task of List&lt;string&gt;</returns>
            public async System.Threading.Tasks.Task<List<string>> GetGuidAliasTypesAsync ()
                {
            ApiResponse<List<string>> localVarResponse = await GetGuidAliasTypesAsyncWithHttpInfo();
                return localVarResponse.Data;

                }

                /// <summary>
                /// List all supported alias types Retrieve this list to find out all alias types to use with alias search and change operations
                /// </summary>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <returns>Task of ApiResponse (List&lt;string&gt;)</returns>
                public async System.Threading.Tasks.Task<ApiResponse<List<string>>> GetGuidAliasTypesAsyncWithHttpInfo ()
                {

                var localVarPath = "./api/v1/search/guids/aliases/types";
                var localVarPathParams = new Dictionary<String, String>();
                var localVarQueryParams = new List<KeyValuePair<String, String>>();
                var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
                var localVarFormParams = new Dictionary<String, String>();
                var localVarFileParams = new Dictionary<String, FileParameter>();
                Object localVarPostBody = null;

                // to determine the Content-Type header
                String[] localVarHttpContentTypes = new String[] {
                    "application/xml", 
                    "application/json"
                };
                String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

                // to determine the Accept header
                String[] localVarHttpHeaderAccepts = new String[] {
                    "application/xml",
                    "application/json"
                };
                String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
                if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


                    // authentication (Authorization) required
                            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
                            {
                            localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
                            }

                // make the HTTP request
                IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

                int localVarStatusCode = (int) localVarResponse.StatusCode;

                if (ExceptionFactory != null)
                {
                Exception exception = ExceptionFactory("GetGuidAliasTypes", localVarResponse);
                if (exception != null) throw exception;
                }

                    return new ApiResponse<List<string>>(localVarStatusCode,
                    localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                    (List<string>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<string>)));
                }

            /// <summary>
            /// Get all aliases for the given GUID. Looks up the alias for each alias type (group and single GUID) and returns a map of all aliases found.
            /// </summary>
            /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id4n">The GUID to operate on</param>
        /// <returns>Dictionary&lt;string, string&gt;</returns>
            public Dictionary<string, string> GetGuidAliases (string id4n)
            {
        ApiResponse<Dictionary<string, string>> localVarResponse = GetGuidAliasesWithHttpInfo(id4n);
            return localVarResponse.Data;
            }

            /// <summary>
            /// Get all aliases for the given GUID. Looks up the alias for each alias type (group and single GUID) and returns a map of all aliases found.
            /// </summary>
            /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id4n">The GUID to operate on</param>
        /// <returns>ApiResponse of Dictionary&lt;string, string&gt;</returns>
            public ApiResponse< Dictionary<string, string> > GetGuidAliasesWithHttpInfo (string id4n)
            {
                    // verify the required parameter 'id4n' is set
                    if (id4n == null)
                    throw new ApiException(400, "Missing required parameter 'id4n' when calling AliasApi->GetGuidAliases");

            var localVarPath = "./api/v1/guids/{id4n}/alias";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/xml", 
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml",
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

                if (id4n != null) localVarPathParams.Add("id4n", Configuration.ApiClient.ParameterToString(id4n)); // path parameter

                // authentication (Authorization) required
                        if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
                        {
                        localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
                        }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
            Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
            Exception exception = ExceptionFactory("GetGuidAliases", localVarResponse);
            if (exception != null) throw exception;
            }

                return new ApiResponse<Dictionary<string, string>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (Dictionary<string, string>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Dictionary<string, string>)));
            }

                /// <summary>
                /// Get all aliases for the given GUID. Looks up the alias for each alias type (group and single GUID) and returns a map of all aliases found.
                /// </summary>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="id4n">The GUID to operate on</param>
            /// <returns>Task of Dictionary&lt;string, string&gt;</returns>
            public async System.Threading.Tasks.Task<Dictionary<string, string>> GetGuidAliasesAsync (string id4n)
                {
            ApiResponse<Dictionary<string, string>> localVarResponse = await GetGuidAliasesAsyncWithHttpInfo(id4n);
                return localVarResponse.Data;

                }

                /// <summary>
                /// Get all aliases for the given GUID. Looks up the alias for each alias type (group and single GUID) and returns a map of all aliases found.
                /// </summary>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="id4n">The GUID to operate on</param>
            /// <returns>Task of ApiResponse (Dictionary&lt;string, string&gt;)</returns>
                public async System.Threading.Tasks.Task<ApiResponse<Dictionary<string, string>>> GetGuidAliasesAsyncWithHttpInfo (string id4n)
                {
                        // verify the required parameter 'id4n' is set
                        if (id4n == null)
                        throw new ApiException(400, "Missing required parameter 'id4n' when calling AliasApi->GetGuidAliases");

                var localVarPath = "./api/v1/guids/{id4n}/alias";
                var localVarPathParams = new Dictionary<String, String>();
                var localVarQueryParams = new List<KeyValuePair<String, String>>();
                var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
                var localVarFormParams = new Dictionary<String, String>();
                var localVarFileParams = new Dictionary<String, FileParameter>();
                Object localVarPostBody = null;

                // to determine the Content-Type header
                String[] localVarHttpContentTypes = new String[] {
                    "application/xml", 
                    "application/json"
                };
                String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

                // to determine the Accept header
                String[] localVarHttpHeaderAccepts = new String[] {
                    "application/xml",
                    "application/json"
                };
                String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
                if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

                    if (id4n != null) localVarPathParams.Add("id4n", Configuration.ApiClient.ParameterToString(id4n)); // path parameter

                    // authentication (Authorization) required
                            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
                            {
                            localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
                            }

                // make the HTTP request
                IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

                int localVarStatusCode = (int) localVarResponse.StatusCode;

                if (ExceptionFactory != null)
                {
                Exception exception = ExceptionFactory("GetGuidAliases", localVarResponse);
                if (exception != null) throw exception;
                }

                    return new ApiResponse<Dictionary<string, string>>(localVarStatusCode,
                    localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                    (Dictionary<string, string>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Dictionary<string, string>)));
                }

            /// <summary>
            /// Remove aliases from GUIDs Remove the alias of the given type
            /// </summary>
            /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id4n">The GUID to operate on</param>
        /// <param name="aliasType">Alias type, see the corresponding API model</param>
        /// <returns></returns>
            public void RemoveGuidAlias (string id4n, string aliasType)
            {
        RemoveGuidAliasWithHttpInfo(id4n, aliasType);
            }

            /// <summary>
            /// Remove aliases from GUIDs Remove the alias of the given type
            /// </summary>
            /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id4n">The GUID to operate on</param>
        /// <param name="aliasType">Alias type, see the corresponding API model</param>
        /// <returns>ApiResponse of Object(void)</returns>
            public ApiResponse<Object> RemoveGuidAliasWithHttpInfo (string id4n, string aliasType)
            {
                    // verify the required parameter 'id4n' is set
                    if (id4n == null)
                    throw new ApiException(400, "Missing required parameter 'id4n' when calling AliasApi->RemoveGuidAlias");
                    // verify the required parameter 'aliasType' is set
                    if (aliasType == null)
                    throw new ApiException(400, "Missing required parameter 'aliasType' when calling AliasApi->RemoveGuidAlias");

            var localVarPath = "./api/v1/guids/{id4n}/alias/{aliasType}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/xml", 
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml",
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

                if (id4n != null) localVarPathParams.Add("id4n", Configuration.ApiClient.ParameterToString(id4n)); // path parameter
                if (aliasType != null) localVarPathParams.Add("aliasType", Configuration.ApiClient.ParameterToString(aliasType)); // path parameter

                // authentication (Authorization) required
                        if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
                        {
                        localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
                        }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
            Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
            Exception exception = ExceptionFactory("RemoveGuidAlias", localVarResponse);
            if (exception != null) throw exception;
            }

                return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                null);
            }

                /// <summary>
                /// Remove aliases from GUIDs Remove the alias of the given type
                /// </summary>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="id4n">The GUID to operate on</param>
            /// <param name="aliasType">Alias type, see the corresponding API model</param>
            /// <returns>Task of void</returns>
            public async System.Threading.Tasks.Task RemoveGuidAliasAsync (string id4n, string aliasType)
                {
            await RemoveGuidAliasAsyncWithHttpInfo(id4n, aliasType);

                }

                /// <summary>
                /// Remove aliases from GUIDs Remove the alias of the given type
                /// </summary>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="id4n">The GUID to operate on</param>
            /// <param name="aliasType">Alias type, see the corresponding API model</param>
            /// <returns>Task of ApiResponse</returns>
                public async System.Threading.Tasks.Task<ApiResponse<Object>> RemoveGuidAliasAsyncWithHttpInfo (string id4n, string aliasType)
                {
                        // verify the required parameter 'id4n' is set
                        if (id4n == null)
                        throw new ApiException(400, "Missing required parameter 'id4n' when calling AliasApi->RemoveGuidAlias");
                        // verify the required parameter 'aliasType' is set
                        if (aliasType == null)
                        throw new ApiException(400, "Missing required parameter 'aliasType' when calling AliasApi->RemoveGuidAlias");

                var localVarPath = "./api/v1/guids/{id4n}/alias/{aliasType}";
                var localVarPathParams = new Dictionary<String, String>();
                var localVarQueryParams = new List<KeyValuePair<String, String>>();
                var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
                var localVarFormParams = new Dictionary<String, String>();
                var localVarFileParams = new Dictionary<String, FileParameter>();
                Object localVarPostBody = null;

                // to determine the Content-Type header
                String[] localVarHttpContentTypes = new String[] {
                    "application/xml", 
                    "application/json"
                };
                String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

                // to determine the Accept header
                String[] localVarHttpHeaderAccepts = new String[] {
                    "application/xml",
                    "application/json"
                };
                String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
                if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

                    if (id4n != null) localVarPathParams.Add("id4n", Configuration.ApiClient.ParameterToString(id4n)); // path parameter
                    if (aliasType != null) localVarPathParams.Add("aliasType", Configuration.ApiClient.ParameterToString(aliasType)); // path parameter

                    // authentication (Authorization) required
                            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
                            {
                            localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
                            }

                // make the HTTP request
                IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

                int localVarStatusCode = (int) localVarResponse.StatusCode;

                if (ExceptionFactory != null)
                {
                Exception exception = ExceptionFactory("RemoveGuidAlias", localVarResponse);
                if (exception != null) throw exception;
                }

                    return new ApiResponse<Object>(localVarStatusCode,
                    localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                    null);
                }

            /// <summary>
            /// Search for GUIDs by alias 
            /// </summary>
            /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alias">The alias to search for</param>
        /// <param name="aliasType">Alias type type to search for</param>
        /// <param name="offset">Start with the n-th element (optional)</param>
        /// <param name="limit">The maximum count of returned elements (optional)</param>
        /// <returns>PaginatedGuidResponse</returns>
            public PaginatedGuidResponse SearchByAlias (string alias, string aliasType, int? offset = null, int? limit = null)
            {
        ApiResponse<PaginatedGuidResponse> localVarResponse = SearchByAliasWithHttpInfo(alias, aliasType, offset, limit);
            return localVarResponse.Data;
            }

            /// <summary>
            /// Search for GUIDs by alias 
            /// </summary>
            /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alias">The alias to search for</param>
        /// <param name="aliasType">Alias type type to search for</param>
        /// <param name="offset">Start with the n-th element (optional)</param>
        /// <param name="limit">The maximum count of returned elements (optional)</param>
        /// <returns>ApiResponse of PaginatedGuidResponse</returns>
            public ApiResponse< PaginatedGuidResponse > SearchByAliasWithHttpInfo (string alias, string aliasType, int? offset = null, int? limit = null)
            {
                    // verify the required parameter 'alias' is set
                    if (alias == null)
                    throw new ApiException(400, "Missing required parameter 'alias' when calling AliasApi->SearchByAlias");
                    // verify the required parameter 'aliasType' is set
                    if (aliasType == null)
                    throw new ApiException(400, "Missing required parameter 'aliasType' when calling AliasApi->SearchByAlias");

            var localVarPath = "./api/v1/search/guids";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/xml", 
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml",
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

                if (alias != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "alias", alias)); // query parameter
                if (aliasType != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "aliasType", aliasType)); // query parameter
                if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
                if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

                // authentication (Authorization) required
                        if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
                        {
                        localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
                        }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
            Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
            Exception exception = ExceptionFactory("SearchByAlias", localVarResponse);
            if (exception != null) throw exception;
            }

                return new ApiResponse<PaginatedGuidResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PaginatedGuidResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PaginatedGuidResponse)));
            }

                /// <summary>
                /// Search for GUIDs by alias 
                /// </summary>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="alias">The alias to search for</param>
            /// <param name="aliasType">Alias type type to search for</param>
            /// <param name="offset">Start with the n-th element (optional)</param>
            /// <param name="limit">The maximum count of returned elements (optional)</param>
            /// <returns>Task of PaginatedGuidResponse</returns>
            public async System.Threading.Tasks.Task<PaginatedGuidResponse> SearchByAliasAsync (string alias, string aliasType, int? offset = null, int? limit = null)
                {
            ApiResponse<PaginatedGuidResponse> localVarResponse = await SearchByAliasAsyncWithHttpInfo(alias, aliasType, offset, limit);
                return localVarResponse.Data;

                }

                /// <summary>
                /// Search for GUIDs by alias 
                /// </summary>
                /// <exception cref="BlueRain.ID4i.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="alias">The alias to search for</param>
            /// <param name="aliasType">Alias type type to search for</param>
            /// <param name="offset">Start with the n-th element (optional)</param>
            /// <param name="limit">The maximum count of returned elements (optional)</param>
            /// <returns>Task of ApiResponse (PaginatedGuidResponse)</returns>
                public async System.Threading.Tasks.Task<ApiResponse<PaginatedGuidResponse>> SearchByAliasAsyncWithHttpInfo (string alias, string aliasType, int? offset = null, int? limit = null)
                {
                        // verify the required parameter 'alias' is set
                        if (alias == null)
                        throw new ApiException(400, "Missing required parameter 'alias' when calling AliasApi->SearchByAlias");
                        // verify the required parameter 'aliasType' is set
                        if (aliasType == null)
                        throw new ApiException(400, "Missing required parameter 'aliasType' when calling AliasApi->SearchByAlias");

                var localVarPath = "./api/v1/search/guids";
                var localVarPathParams = new Dictionary<String, String>();
                var localVarQueryParams = new List<KeyValuePair<String, String>>();
                var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
                var localVarFormParams = new Dictionary<String, String>();
                var localVarFileParams = new Dictionary<String, FileParameter>();
                Object localVarPostBody = null;

                // to determine the Content-Type header
                String[] localVarHttpContentTypes = new String[] {
                    "application/xml", 
                    "application/json"
                };
                String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

                // to determine the Accept header
                String[] localVarHttpHeaderAccepts = new String[] {
                    "application/xml",
                    "application/json"
                };
                String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
                if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

                    if (alias != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "alias", alias)); // query parameter
                    if (aliasType != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "aliasType", aliasType)); // query parameter
                    if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
                    if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

                    // authentication (Authorization) required
                            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
                            {
                            localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
                            }

                // make the HTTP request
                IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

                int localVarStatusCode = (int) localVarResponse.StatusCode;

                if (ExceptionFactory != null)
                {
                Exception exception = ExceptionFactory("SearchByAlias", localVarResponse);
                if (exception != null) throw exception;
                }

                    return new ApiResponse<PaginatedGuidResponse>(localVarStatusCode,
                    localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                    (PaginatedGuidResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PaginatedGuidResponse)));
                }

        }
    }